// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: tits/v1/tits_service.proto

package titsv1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Enum with ordering types
type TitsFilterEnum_Enum int32

const (
	// Random ordering.
	TitsFilterEnum_RANDOM TitsFilterEnum_Enum = 0
	// Order by rating desc.
	TitsFilterEnum_TOP TitsFilterEnum_Enum = 1
)

// Enum value maps for TitsFilterEnum_Enum.
var (
	TitsFilterEnum_Enum_name = map[int32]string{
		0: "RANDOM",
		1: "TOP",
	}
	TitsFilterEnum_Enum_value = map[string]int32{
		"RANDOM": 0,
		"TOP":    1,
	}
)

func (x TitsFilterEnum_Enum) Enum() *TitsFilterEnum_Enum {
	p := new(TitsFilterEnum_Enum)
	*p = x
	return p
}

func (x TitsFilterEnum_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TitsFilterEnum_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_tits_v1_tits_service_proto_enumTypes[0].Descriptor()
}

func (TitsFilterEnum_Enum) Type() protoreflect.EnumType {
	return &file_tits_v1_tits_service_proto_enumTypes[0]
}

func (x TitsFilterEnum_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TitsFilterEnum_Enum.Descriptor instead.
func (TitsFilterEnum_Enum) EnumDescriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{0, 0}
}

type RateTypeEnum_Enum int32

const (
	RateTypeEnum_VOTE   RateTypeEnum_Enum = 0
	RateTypeEnum_REPORT RateTypeEnum_Enum = 1
)

// Enum value maps for RateTypeEnum_Enum.
var (
	RateTypeEnum_Enum_name = map[int32]string{
		0: "VOTE",
		1: "REPORT",
	}
	RateTypeEnum_Enum_value = map[string]int32{
		"VOTE":   0,
		"REPORT": 1,
	}
)

func (x RateTypeEnum_Enum) Enum() *RateTypeEnum_Enum {
	p := new(RateTypeEnum_Enum)
	*p = x
	return p
}

func (x RateTypeEnum_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateTypeEnum_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_tits_v1_tits_service_proto_enumTypes[1].Descriptor()
}

func (RateTypeEnum_Enum) Type() protoreflect.EnumType {
	return &file_tits_v1_tits_service_proto_enumTypes[1]
}

func (x RateTypeEnum_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateTypeEnum_Enum.Descriptor instead.
func (RateTypeEnum_Enum) EnumDescriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{4, 0}
}

// Enum for GetTitsRequest with ordering types.
type TitsFilterEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TitsFilterEnum) Reset() {
	*x = TitsFilterEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TitsFilterEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitsFilterEnum) ProtoMessage() {}

func (x *TitsFilterEnum) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitsFilterEnum.ProtoReflect.Descriptor instead.
func (*TitsFilterEnum) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{0}
}

// Filter for get TitsRequest
type GetTitsFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Count of tits to receive.
	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Tits ordering.
	Ordering TitsFilterEnum_Enum `protobuf:"varint,3,opt,name=ordering,proto3,enum=tits.v1.TitsFilterEnum_Enum" json:"ordering,omitempty"`
}

func (x *GetTitsFilter) Reset() {
	*x = GetTitsFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTitsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTitsFilter) ProtoMessage() {}

func (x *GetTitsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTitsFilter.ProtoReflect.Descriptor instead.
func (*GetTitsFilter) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTitsFilter) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetTitsFilter) GetOrdering() TitsFilterEnum_Enum {
	if x != nil {
		return x.Ordering
	}
	return TitsFilterEnum_RANDOM
}

// GetTitsRequest
type GetTitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *GetTitsFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetTitsRequest) Reset() {
	*x = GetTitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTitsRequest) ProtoMessage() {}

func (x *GetTitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTitsRequest.ProtoReflect.Descriptor instead.
func (*GetTitsRequest) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTitsRequest) GetFilter() *GetTitsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GetTitsResponse
type GetTitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Tits
	Tits []*Tits `protobuf:"bytes,1,rep,name=tits,proto3" json:"tits,omitempty"`
}

func (x *GetTitsResponse) Reset() {
	*x = GetTitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTitsResponse) ProtoMessage() {}

func (x *GetTitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTitsResponse.ProtoReflect.Descriptor instead.
func (*GetTitsResponse) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTitsResponse) GetTits() []*Tits {
	if x != nil {
		return x.Tits
	}
	return nil
}

// Enum for RateTitsRequest with vote types.
type RateTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RateTypeEnum) Reset() {
	*x = RateTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateTypeEnum) ProtoMessage() {}

func (x *RateTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateTypeEnum.ProtoReflect.Descriptor instead.
func (*RateTypeEnum) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{4}
}

type RateTitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitsId   string            `protobuf:"bytes,1,opt,name=tits_id,json=titsId,proto3" json:"tits_id,omitempty"`
	RateType RateTypeEnum_Enum `protobuf:"varint,2,opt,name=rate_type,json=rateType,proto3,enum=tits.v1.RateTypeEnum_Enum" json:"rate_type,omitempty"`
}

func (x *RateTitsRequest) Reset() {
	*x = RateTitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateTitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateTitsRequest) ProtoMessage() {}

func (x *RateTitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateTitsRequest.ProtoReflect.Descriptor instead.
func (*RateTitsRequest) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{5}
}

func (x *RateTitsRequest) GetTitsId() string {
	if x != nil {
		return x.TitsId
	}
	return ""
}

func (x *RateTitsRequest) GetRateType() RateTypeEnum_Enum {
	if x != nil {
		return x.RateType
	}
	return RateTypeEnum_VOTE
}

type RateTitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RateTitsResponse) Reset() {
	*x = RateTitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateTitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateTitsResponse) ProtoMessage() {}

func (x *RateTitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateTitsResponse.ProtoReflect.Descriptor instead.
func (*RateTitsResponse) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_service_proto_rawDescGZIP(), []int{6}
}

var File_tits_v1_tits_service_proto protoreflect.FileDescriptor

var file_tits_v1_tits_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x12, 0x74, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x54, 0x69, 0x74,
	0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x1b, 0x0a, 0x04, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x54, 0x4f, 0x50, 0x10, 0x01, 0x22, 0x61, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54,
	0x69, 0x74, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x38, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69,
	0x74, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x40, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x73, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x34, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x74, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x74, 0x73, 0x52, 0x04, 0x74,
	0x69, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x22, 0x1c, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x56,
	0x4f, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x10,
	0x01, 0x22, 0x63, 0x0a, 0x0f, 0x52, 0x61, 0x74, 0x65, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x73, 0x49, 0x64, 0x12, 0x37, 0x0a,
	0x09, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x72, 0x61,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x90, 0x01, 0x0a, 0x0b, 0x54,
	0x69, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08, 0x52, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x61, 0x74, 0x65, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x74, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x69, 0x74, 0x73, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tits_v1_tits_service_proto_rawDescOnce sync.Once
	file_tits_v1_tits_service_proto_rawDescData = file_tits_v1_tits_service_proto_rawDesc
)

func file_tits_v1_tits_service_proto_rawDescGZIP() []byte {
	file_tits_v1_tits_service_proto_rawDescOnce.Do(func() {
		file_tits_v1_tits_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tits_v1_tits_service_proto_rawDescData)
	})
	return file_tits_v1_tits_service_proto_rawDescData
}

var file_tits_v1_tits_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tits_v1_tits_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tits_v1_tits_service_proto_goTypes = []interface{}{
	(TitsFilterEnum_Enum)(0), // 0: tits.v1.TitsFilterEnum.Enum
	(RateTypeEnum_Enum)(0),   // 1: tits.v1.RateTypeEnum.Enum
	(*TitsFilterEnum)(nil),   // 2: tits.v1.TitsFilterEnum
	(*GetTitsFilter)(nil),    // 3: tits.v1.GetTitsFilter
	(*GetTitsRequest)(nil),   // 4: tits.v1.GetTitsRequest
	(*GetTitsResponse)(nil),  // 5: tits.v1.GetTitsResponse
	(*RateTypeEnum)(nil),     // 6: tits.v1.RateTypeEnum
	(*RateTitsRequest)(nil),  // 7: tits.v1.RateTitsRequest
	(*RateTitsResponse)(nil), // 8: tits.v1.RateTitsResponse
	(*Tits)(nil),             // 9: tits.v1.Tits
}
var file_tits_v1_tits_service_proto_depIdxs = []int32{
	0, // 0: tits.v1.GetTitsFilter.ordering:type_name -> tits.v1.TitsFilterEnum.Enum
	3, // 1: tits.v1.GetTitsRequest.filter:type_name -> tits.v1.GetTitsFilter
	9, // 2: tits.v1.GetTitsResponse.tits:type_name -> tits.v1.Tits
	1, // 3: tits.v1.RateTitsRequest.rate_type:type_name -> tits.v1.RateTypeEnum.Enum
	4, // 4: tits.v1.TitsService.GetTits:input_type -> tits.v1.GetTitsRequest
	7, // 5: tits.v1.TitsService.RateTits:input_type -> tits.v1.RateTitsRequest
	5, // 6: tits.v1.TitsService.GetTits:output_type -> tits.v1.GetTitsResponse
	8, // 7: tits.v1.TitsService.RateTits:output_type -> tits.v1.RateTitsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tits_v1_tits_service_proto_init() }
func file_tits_v1_tits_service_proto_init() {
	if File_tits_v1_tits_service_proto != nil {
		return
	}
	file_tits_v1_tits_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tits_v1_tits_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TitsFilterEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTitsFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateTitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateTitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tits_v1_tits_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tits_v1_tits_service_proto_goTypes,
		DependencyIndexes: file_tits_v1_tits_service_proto_depIdxs,
		EnumInfos:         file_tits_v1_tits_service_proto_enumTypes,
		MessageInfos:      file_tits_v1_tits_service_proto_msgTypes,
	}.Build()
	File_tits_v1_tits_service_proto = out.File
	file_tits_v1_tits_service_proto_rawDesc = nil
	file_tits_v1_tits_service_proto_goTypes = nil
	file_tits_v1_tits_service_proto_depIdxs = nil
}
